default:
  data_path: "data/processed/"
  model_save_path: "models/"
  results_save_path: "results/"
  batch_size: 512

detection:
  data_filename: "detection_data.h5"
  model_filename: "drone_detection_model.pth"
  model_architecture: "cnn"
  feature_method: "log_mel_mfcc_stack" 
  epochs: 10
  learning_rate: 0.001
  class_names: ["Non-Drone", "Drone"]

distance:
  data_filename: "distance_data.h5"
  model_filename: "drone_distance_model.pth"
  model_architecture: "lstm"
  feature_method: "mfcc_sequence"
  epochs: 100
  learning_rate: 0.001
  lstm_hidden_size: 128
  lstm_num_layers: 2