default:
  data_path: "data/processed/"
  model_save_path: "models/"
  results_save_path: "results/"
  batch_size: 128

detection:
  data_filename: "detection_data.npz"
  model_filename: "drone_detection_model.pth"
  model_architecture: "cnn" 
  feature_method: "log_mel_mfcc_stack" 
  epochs: 10
  learning_rate: 0.001
  class_names: ["Non-Drone", "Drone"]

distance_cnn:
  data_filename: "distance_cnn_data.npz" 
  model_filename: "drone_distance_cnn_model.pth" 
  model_architecture: "cnn" 
  feature_method: "log_mel_mfcc_stack" 
  epochs: 10
  learning_rate: 0.001

distance_mlp:
  data_filename: "distance_mlp_data.npz" 
  model_filename: "drone_distance_mlp_model.pth" 
  model_architecture: "mlp" 
  feature_method: "mfcc_mean" 
  epochs: 10
  learning_rate: 0.001